package dev.repomind.core.report

import dev.repomind.core.graph.InMemoryGraph
import dev.repomind.core.impact.ImpactAnalyzer
import dev.repomind.core.model.code.Confidence
import dev.repomind.core.model.code.DependencyEdge
import dev.repomind.core.model.code.EdgeKind
import dev.repomind.storage.sqlite.SymbolDatabase
import java.nio.file.Path

class ReportGenerator(
    private val dbPath: Path,
    private val repoName: String,
    private val engineVersion: String = "0.1.0",
) {

    fun generate(): String {
        SymbolDatabase.open(dbPath).use { db ->
            val graph = InMemoryGraph(
                db.edges.findAll().map { row ->
                    DependencyEdge(row.sourceFqn, row.targetFqn, EdgeKind.valueOf(row.kind), Confidence.valueOf(row.confidence))
                },
            )
            val types = db.allTypes().map { TypeInfo(it.qualifiedName, it.kind, it.visibility, it.annotations) }
            val typeModule = db.allTypes().associate { it.qualifiedName to it.module }

            val overview = overviewSection(db, graph)
            val architecture = architectureSection(db, graph, types, typeModule)
            val flows = flowsSection(graph, types)
            val hotspots = hotspotsSection(graph, types)
            val improvements = improvementsSection(graph, types)
            val smells = smellsSection(graph, types)
            val appendix = appendixSection(db, graph)

            return buildString {
                appendLine("# Analysis: $repoName")
                appendLine()
                appendLine("_Generated by RepoMind $engineVersion - deterministic output from the indexed graph._")
                appendLine()
                appendLine("## 1. Overview")
                appendLine(overview)
                appendLine()
                appendLine("## 2. Architecture")
                appendLine(architecture)
                appendLine()
                appendLine("## 3. Key Flows")
                appendLine(flows.ifBlank { "_No entry-point flows detected (no Spring web/application stereotypes found)._" })
                appendLine()
                appendLine("## 4. Hotspots")
                appendLine(hotspots.ifBlank { "_No hotspot candidates (no caller relationships indexed)._" })
                appendLine()
                appendLine("## 5. Points of Improvement")
                appendLine(improvements)
                appendLine()
                appendLine("## 6. Code Smells & Risk Findings")
                appendLine(smells.ifBlank { "_No findings from the enabled deterministic detectors._" })
                appendLine()
                appendLine("## 7. Appendix")
                appendLine(appendix)
            }.trimEnd() + "\n"
        }
    }

    internal fun overviewSection(db: SymbolDatabase, graph: InMemoryGraph): String {
        val modules = db.allTypes().map { it.module }.distinct().sorted()
        val typeRows = db.allTypes()
        val totalTypes = typeRows.size
        val testTypes = typeRows.count { it.name.endsWith("Test") || it.name.endsWith("Tests") }
        val edgeCounts = EdgeKind.entries.associateWith { kind ->
            graph.adjacency.edgeCount.takeIf { false }?.let { 0 } ?: countEdges(graph, kind)
        }
        return buildString {
            appendLine("- **Modules:** ${modules.size} (${modules.joinToString(", ")})")
            appendLine("- **Top-level types:** $totalTypes (test-suffixed: $testTypes)")
            appendLine("- **Edges by kind:** " + edgeCounts.entries.joinToString(", ") { "${it.key}=${it.value}" })
        }.lineSequence().joinToString("\n")
    }

    private fun countEdges(graph: InMemoryGraph, kind: EdgeKind): Int =
        graph.adjacency.outgoing.values.sumOf { edges -> edges.count { it.kind == kind } }

    internal fun architectureSection(
        db: SymbolDatabase,
        graph: InMemoryGraph,
        types: List<TypeInfo>,
        typeModule: Map<String, String>,
    ): String {
        val modules = typeModule.values.distinct().sorted()
        val crossModule = graph.adjacency.outgoing.entries
            .flatMap { (source, edges) ->
                val sourceModule = typeModule[source] ?: return@flatMap emptyList<Pair<String, String>>()
                edges.filter { it.kind == EdgeKind.IMPORTS || it.kind == EdgeKind.USES || it.kind == EdgeKind.CALLS }
                    .mapNotNull { edge ->
                        val targetModule = typeModule[edge.targetFqn.substringBefore('#')]
                        if (targetModule != null && targetModule != sourceModule) sourceModule to targetModule else null
                    }
            }
            .distinct()

        val packageWeights = aggregatePackageEdges(graph, types)
        val stereotypeLabels = packageStereotypes(types)

        return buildString {
            appendLine("### Module diagram")
            appendLine()
            appendLine(MermaidEmitter.moduleDiagram(modules, crossModule))
            appendLine()
            appendLine("### Package dependencies (top ${MAX_PACKAGES} by weight)")
            appendLine()
            appendLine(MermaidEmitter.packageDiagram(stereotypeLabels.keys.toList(), packageWeights, maxNodes = MAX_PACKAGES, stereotypeLabels = stereotypeLabels))
            appendLine()
            appendLine("**Detected stereotypes:** " + stereotypeSummary(types))
        }.trimEnd()
    }

    private val MAX_PACKAGES = 25

    private fun aggregatePackageEdges(graph: InMemoryGraph, types: List<TypeInfo>): List<Triple<String, String, Int>> {
        val localPackages = types.map { it.fqn.substringBeforeLast('.', "") }.toSet()
        val weights = mutableMapOf<Pair<String, String>, Int>()
        for ((source, edges) in graph.adjacency.outgoing) {
            val from = source.substringBeforeLast('.', "")
            for (edge in edges) {
                if (edge.kind == EdgeKind.TESTS) continue
                val to = edge.targetFqn.substringBefore('#').substringBeforeLast('.', "")
                if (from in localPackages && to in localPackages && from != to) {
                    weights[from to to] = (weights[from to to] ?: 0) + 1
                }
            }
        }
        return weights.map { (pair, w) -> Triple(pair.first, pair.second, w) }.sortedByDescending { it.third }
    }

    private fun packageStereotypes(types: List<TypeInfo>): Map<String, String> {
        val byPackage = types.groupBy { it.fqn.substringBeforeLast('.', "") }
        return byPackage.mapValues { (_, members) ->
            val counts = sortedMapOf<String, Int>()
            for (t in members) {
                for (a in t.annotations) {
                    if (a in STEREOTYPE_ORDER) counts[a] = (counts[a] ?: 0) + 1
                }
            }
            if (counts.isEmpty()) "" else counts.entries.joinToString(" ") { "${it.value}×${it.key}" }
        }.filterValues { it.isNotBlank() }
    }

    private fun stereotypeSummary(types: List<TypeInfo>): String =
        STEREOTYPE_ORDER.joinToString(", ") { st ->
            "$st×${types.count { st in it.annotations }}"
        }.let { if (types.none { t -> t.annotations.any { it in STEREOTYPE_ORDER } }) "none detected" else it }

    internal fun flowsSection(graph: InMemoryGraph, types: List<TypeInfo>): String {
        val flows = FlowDetector().detect(graph, types)
        if (flows.isEmpty()) return ""
        return flows.joinToString("\n\n") { flow ->
            "#### ${flow.name}\n\n" +
                MermaidEmitter.flowDiagram(flow.name, flow.participants, flow.dashedFromIndex) +
                "\n\nParticipants: " + flow.participants.joinToString(" -> ")
        }
    }

    internal fun hotspotsSection(graph: InMemoryGraph, types: List<TypeInfo>): String {
        val analyzer = ImpactAnalyzer(graph)
        val candidates = graph.adjacency.incoming.entries
            .filter { it.value.any { e -> e.kind == EdgeKind.CALLS } }
            .sortedByDescending { entry -> entry.value.count { it.kind == EdgeKind.CALLS } }
            .take(50)
            .map { it.key }
        val reports = candidates.mapNotNull { fqn ->
            val meta = types.firstOrNull { it.fqn == fqn }?.let { dev.repomind.core.impact.SymbolMeta(it.kind, it.visibility, it.annotations) }
            analyzer.analyze(fqn, meta) to fqn
        }.filter { (report, _) -> report.score >= 21 }
            .sortedByDescending { (report, _) -> report.score }
            .take(10)

        if (reports.isEmpty()) return ""

        return buildString {
            appendLine("| Symbol | Score | Level | Callers | Tests affected |")
            appendLine("|---|---|---|---|---|")
            for ((report, _) in reports) {
                appendLine("| ${report.symbol} | ${report.score} | ${report.level} | ${report.transitiveCallerCount} | ${report.affectedTestCount} |")
            }
        }.trimEnd()
    }

    internal fun improvementsSection(graph: InMemoryGraph, types: List<TypeInfo>): String {
        val lines = mutableListOf<String>()
        val untestedPublic = types.filter { t ->
            t.visibility == "PUBLIC" && !t.fqn.substringAfterLast('.').endsWith("Test") &&
                graph.adjacency.incoming[t.fqn].orEmpty().none { e -> e.kind == EdgeKind.TESTS } &&
                graph.adjacency.outgoing[t.fqn].orEmpty().isNotEmpty()
        }
        if (untestedPublic.isNotEmpty()) {
            lines += "- **Untested public API:** ${untestedPublic.size} public types have no TESTS edge. Examples: " +
                untestedPublic.take(5).joinToString(", ") { "`${it.fqn}`" }
        }
        val possibleCalls = countEdges(graph, EdgeKind.CALLS).let { total ->
            total to graph.adjacency.outgoing.values.sumOf { e -> e.count { it.kind == EdgeKind.CALLS && it.confidence == Confidence.POSSIBLE } }
        }
        if (possibleCalls.first > 0) {
            lines += "- **Resolution quality:** ${possibleCalls.second}/${possibleCalls.first} CALLS edges are POSSIBLE-only; " +
                "resolving full classpaths (Maven/Gradle on PATH during `repomind index`) converts these to CONFIRMED."
        }
        lines += "- **Architecture rules:** add a `.repomind/rules.yaml` to enforce layering (see docs/analysis-reports-plan.md); violations then feed impact scores."
        return lines.joinToString("\n")
    }

    internal fun smellsSection(graph: InMemoryGraph, types: List<TypeInfo>): String {
        val findings = SmellDetectors().run(graph, types)
        if (findings.isEmpty()) return ""
        return findings.joinToString("\n\n") { finding ->
            "**[${finding.severity.uppercase()}] ${finding.detector}** - ${finding.summary}\n" +
                finding.evidence.joinToString("\n") { "  - $it" }
        }
    }

    internal fun appendixSection(db: SymbolDatabase, graph: InMemoryGraph): String = buildString {
        appendLine("- Engine version: $engineVersion")
        appendLine("- Symbols in index: ${db.count()}")
        appendLine("- Edges in index: ${graph.adjacency.edgeCount}")
        appendLine("- Structural vulnerability scanning is out of scope; findings above are structural only.")
    }.trimEnd()

    companion object {
        private val STEREOTYPE_ORDER = listOf("RestController", "Controller", "Service", "Repository", "Entity", "Component", "Configuration", "SpringBootApplication", "FeignClient")
    }
}
